### ISSUE TITLE
Latest binary is detected as virus

### ISSUE THREAD

**Issue by 0xqab** [dgis/xsddiagram#10]
Latest binary linked on http://regis.cosnier.free.fr/?page=XSDDiagram is a virus according to multiple scanners:

https://virustotal.com/de/file/c611b76b60b010f236778b8e7cb07e46143a4c4c7d0556c6fdeb38111a0f04c1/analysis/1463739594/

**Comment by dgis** [comment]
Thank you to alert me.
I rebuild and recreate the ZIP file, and here the analysis: 
https://www.virustotal.com/en/file/c02c5f3e0442049a7a70c20386fbb871c895ebe7eff062adbb6f32944457ab03/analysis/

Now, each individual exe files is not detected, but the ZIP file "XSDDiagram-2016-02-28-1.0-Binary.zip" is detected with issues. Now, it seems that the issue is the combination of the 2 exe.

Anyway, it is a false positive!

**Comment by dgis** [comment]
The latest binaries do not say that anymore. So, I close!
