### ISSUE TITLE
'annotation.documentation' tag in diagram

### ISSUE THREAD

**Issue by axel3rd** [dgis/xsddiagram#4]
Hi, 

*XSD Diagram* is currently the best *free XSD viewer* I found (easy to use, works fine with *choice in a sequence* tag, ...).

Is there a way to add the "annotation.**description**" tag in diagram view ? This is very useful when we present the schema as a picture.

Thanks in advance.
Best regards.

**Comment by dgis** [comment]
Hi,

Thank you for the compliment.
I understand that it could be great to automatically add the description in the diagram, but it seems complex, because a description has a variable size (width and/or height).
But may be, we could imagine to add the first 2 or 3 lines of text under the element like in this snapshot?
![clip_image005_thumb](https://cloud.githubusercontent.com/assets/620030/10098247/35d1b3d4-6380-11e5-8a38-64995fa9ec28.png)

Best regards,
Régis

**Comment by cinhtau** [comment]
:+1:

a perfect solution approach, what about having a link that opens in a sepate view or dialog the full description?

**Comment by axel3rd** [comment]
@dgis : Fully agree with this feature specification

**Comment by cinhtau** [comment]
@axel3rd: thats even better :smile:

**Comment by dgis** [comment]
The new version 1.0 includes the documentation (through the toolbar button) :-)

**Comment by axel3rd** [comment]
So nice ! Thank you very much
